# Use Node.js as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to install dependencies
COPY backend_express/package*.json ./

# Install dependencies
RUN npm install

# THIS COMMENT HAS BEEN REMOVED. THANK YOU FOR YOUR UNDERSTANDING.
COPY backend_express/ .

# Expose the application port
EXPOSE 5005

# Command to start the server
CMD ["node", "server.js"]
