# Use Node.js as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to install dependencies
COPY frontend_react/package*.json ./

# Install dependencies
RUN npm install

# THIS COMMENT HAS BEEN REMOVED. THANK YOU FOR YOUR UNDERSTANDING.
COPY frontend_react/ .

# Expose the application port
EXPOSE 3000

# Command to start the server
CMD ["npm", "start"]
